### ISSUE TITLE
Got "locked database" again

### ISSUE THREAD

**Issue by buzzy** [SanderGi/sqlite-auto-migrator#4]
The update was just adding a single TEXT column. No index. It caused this:

![image](https://github.com/user-attachments/assets/2111b53e-8b11-464a-9885-0cd8c9a5537b)

UPDATE: It seems it DID add the field through, but with "" around the name?? The field pushToken was the new one.

<img width="1078" alt="image" src="https://github.com/user-attachments/assets/c1112a82-41c3-44a3-be51-dee00b69a2f9">

**Comment by SanderGi** [comment]
The quotes are part of SQLite syntax (https://www.sqlite.org/lang_keywords.html) and do not effect the column name (they are there to escape any potential special characters and you can still interact with the column name as if the schema did not have quotes since your column does not contain any special characters).

It looks like it succeeded in applying the changes but ran into a lock when verifying your pragmas afterwards (hence why it did add the field). The pragmas are a bit weird since SQLite does not allow setting them in a transaction (and the migration can therefore not be rolled back if there is an issue with the pragmas). It seems it failed to set your journal mode to “memory”. Do you have this set in your schema file? If so, this is not recommended unless you absolutely need the speedup since according to the SQLite docs this “likely leads to database corruption” and comes at the “expense of database safety and integrity”. If you do not have this set in your schema, please send your schema and I’ll take a look at why the library thinks it is set

**Comment by buzzy** [comment]
This is the complete schema file:

```
PRAGMA foreign_keys = on;

-- Table: sessions
CREATE TABLE "sessions" (
  id blob PRIMARY KEY NOT NULL,
  user blob NOT NULL,
  lastChecked timestamp NOT NULL,
  pushToken TEXT
) WITHOUT ROWID;

-- Index: user
CREATE INDEX user ON sessions (user);
```

**Comment by SanderGi** [comment]
I identified the issue. `node-sqlite3` creates a temporary disk database when passed an empty path whereas bun creates an in-memory database and does not have an API for creating a temp disk database:
```js
import { Database } from 'sqlite-auto-migrator';
const db = await Database.connect('');
console.log(await db.get('PRAGMA journal_mode')); // outputs 'memory' with bun and 'delete' with Node.js
```
This means that when diffing, the library uses an in memory database as the baseline for interpreting the schema when used with bun. I have published a fix with version `1.2.1` and will work on running the automated test suite with bun in addition to node (will require rewriting the tests so they are not dependent on the node test runner). Running the migrations again with the new version should fix the issue and automatically revert your database back to journal mode 'delete'. Let me know if that works for you or if you run into any issues

**Comment by buzzy** [comment]
Thanks! I have updated the version in my CI-pipeline and will let you know if I run into any other issues in the future.

**Comment by buzzy** [comment]
Not sure if I did something on my side, but I got LOCKED DATABASE again:

![image](https://github.com/user-attachments/assets/36c5c60c-367f-40b4-8768-f166bbf0e121)

**Comment by SanderGi** [comment]
I am unable to reproduce this bug. Does it occur locally or only with your Windows GitHub actions runner? If you can send your .githubs/workflows file or a minimal example, I can try to use that to reproduce the issue. Is this updating your production database? If so, are you making sure no other connections are trying to access the database while the migrator is running?

**Comment by buzzy** [comment]
It only occurred durring my latest "staging" deployment. It was in a Ubuntu action runner though, not Windows. I am not doing anything that prevents others from accessing the database. I assumed the update simply waits until the database is available (not locked), then locks it it, performs the changes and then unlocks the database. My other connections are using 10 second timeout, so they are fine with waiting for the update to finish. If the migration task is assuming an unlocked database immediately, I would suggest adding the possibility to enter a timeout value for it to wait until the database can be updated instead of bailing out. I don't think that was the reason this time though. My staging environment is pretty much idle.

**Comment by SanderGi** [comment]
Ah, I saw the .exe extension and assumed you were using windows. It would still be helpful to have the workflow file to reproduce the issue. I still cannot reproduce the issue neither locally nor in other action runners with my own workflows.

The migrator does wait to acquire a lock before bailing out for the main update. However the only way to explicitly hold such a lock is during a transaction and pragmas can in general not be executes during a transaction, hence it has to give up the lock before executing the pragmas. I assumed sqlite automatically acquired the lock for pragma statements and used the busy_timeout to wait before bailing out. If that’s not the case and I can reproduce it, I can look into a workaround

**Comment by buzzy** [comment]
I'm afraid I can't reproduce it either, as I ended up manually changing the database. The workflow is not doing anything other than running the migration. The steps before is not doing anything with the database at all. When it happens again, I will make sure to take a copy of the database so that we can reproduce it.

**Comment by SanderGi** [comment]
After [googling around](https://sqlite-users.sqlite.narkive.com/E0PV7xHv/sqlite-pragma-synchronous-safety), it seems that setting the journal_mode from WAL to delete has a very harsh requirement that [at most one database connection is open](https://stackoverflow.com/questions/57118674/go-sqlite3-with-journal-mode-wal-gives-database-is-locked-error): 
![image](https://github.com/user-attachments/assets/a58af3fa-4f6a-4a77-b00e-5d21952b0e6b)
Does your sqlite host automatically set the journal_mode to WAL or do you have other configuration code (e.g. the connection string) that sets the journal_mode by any chance?

**Comment by buzzy** [comment]
Yes, the very beginning of my code opens all the databases and sets them to WAL. Maybe I should just move that part bellow the migration then?

**Comment by SanderGi** [comment]
That would explain the SQLITE_BUSY error. You can move that below or set the journal_mode pragma in the schema instead (then the migrator will ensure it is set since WAL is persisted in the database). Setting it below would be inefficient since the migrator will set the jounal_mode to delete first as that is the default schema value. Generally, all persisted pragmas should be tracked in the schema (the migrator shows you which pragmas are not persisted and should be applied to each connection instead). The migrator expects to be in control of the database state, I’ll make clear in the documentation that this extends to all metadata stored in the database, not just the schema table.

I would still open the connections after the migrator (since otherwise the migrator might run into trouble setting the journal_mode due to conflicts from other connections)

**Comment by SanderGi** [comment]
I could also add a flag for the migrator to ignore pragmas if you would prefer to manage those yourself?

**Comment by buzzy** [comment]
I just added "PRAGMA journal_mode = WAL;" at the top of my .sql files and moved the migration code/import above all my other imports to prevent my code from interfering. I hope that solves my issue :)

**Comment by SanderGi** [comment]
Sounds good. Feel free to open a new issue if the problem surfaces again
